[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_RESOLUTION)sx24 -ac +extension GLX +render -noreset
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb.err

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=":1",HOME="/root",USER="root"
autostart=true
autorestart=true
priority=20
startsecs=3
stdout_logfile=/var/log/xfce.log
stderr_logfile=/var/log/xfce.err

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -rfbauth /root/.vnc/passwd -rfbport 5900 -shared -forever -noxdamage -ncache 10
autostart=true
autorestart=true
priority=30
startsecs=3
stdout_logfile=/var/log/x11vnc.log
stderr_logfile=/var/log/x11vnc.err

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5900
autostart=true
autorestart=true
priority=40
startsecs=3
stdout_logfile=/var/log/novnc.log
stderr_logfile=/var/log/novnc.err
